replicaCount: 2

image:
  repository: anpauthuser.azurecr.io/http-echo-project:58
  pullPolicy: IfNotPresent

deployment:
  containerport: 80


service:
  type: LoadBalancer
  port: 80
  targetport: 80

ingress:
  enabled: false
  className: ""
  port: 80
  hosts:
    - host: 
      paths:
        - path: /
          pathType: Exact
