apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "http-echo-project-chart.fullname" . }}-deployment
  #label:
   #app: {{ include "http-echo-project-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "http-echo-project-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "http-echo-project-chart.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}
        #pullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployment.containerport }}
